before_script:
  - npm install; npm install -g gulp
script: gulp test
language: node_js
env:
  - PORT=7777
node_js:
  - "5.1"
  - "4"
  
# Doesn't work for node_js version:
# "15.7.0", 
# "0.12"
# works for "6" too
